# Generated by Django 5.2.4 on 2025-09-11 01:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0005_migrate_templates_to_global'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='category',
            name='uq_category_user_name',
        ),
        migrations.RemoveConstraint(
            model_name='category',
            name='uq_category_global_name_ci',
        ),
        migrations.RemoveIndex(
            model_name='category',
            name='finance_cat_user_id_70f9d7_idx',
        ),
        migrations.RemoveIndex(
            model_name='category',
            name='finance_cat_name_d54757_idx',
        ),
        migrations.RemoveField(
            model_name='category',
            name='kind',
        ),
        migrations.AddConstraint(
            model_name='category',
            constraint=models.UniqueConstraint(fields=('user', 'name'), name='uniq_user_category_name'),
        ),
        migrations.AddConstraint(
            model_name='category',
            constraint=models.UniqueConstraint(condition=models.Q(('user__isnull', True)), fields=('name',), name='uniq_global_category_name'),
        ),
    ]
