# Generated by Django 5.2.4 on 2025-09-11 22:08

import django.db.models.functions.text
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0006_category_globalize'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='category',
            name='uniq_user_category_name',
        ),
        migrations.RemoveConstraint(
            model_name='category',
            name='uniq_global_category_name',
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(django.db.models.functions.text.Lower('name'), name='idx_category_name_lower'),
        ),
        migrations.AddConstraint(
            model_name='category',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('name'), models.F('user'), name='uniq_user_category_name_insensitive'),
        ),
        migrations.AddConstraint(
            model_name='category',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('name'), condition=models.Q(('user__isnull', True)), name='uniq_global_category_name_insensitive'),
        ),
    ]
