# Generated by Django 5.2.4 on 2025-10-04 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0008_add_wallet'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='transaction',
            name='finance_tra_user_id_f69cf8_idx',
        ),
        migrations.RenameIndex(
            model_name='transaction',
            new_name='finance_tra_wallet__3aa168_idx',
            old_name='txn_wallet_date_idx',
        ),
    ]
