# Generated by Django 5.2.4 on 2025-10-05 22:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0010_wallet_unique_active_only'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='wallet',
            name='uniq_wallet_name_per_user_insensitive',
        ),
    ]
