# Generated by Django 5.2.4 on 2025-10-06 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0011_remove_wallet_uniq_wallet_name_per_user_insensitive'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='kind',
            field=models.CharField(choices=[('checking', 'Conta corrente'), ('savings', 'Poupança'), ('cash', 'Dinheiro'), ('credit', 'Cartão de crédito'), ('investment', 'Investimento'), ('other', 'Outros')], default='checking', max_length=20),
        ),
    ]
