# Generated by Django 5.2.4 on 2025-10-13 00:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0013_goal'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Goal',
        ),
    ]
