# Generated by Django 5.2.4 on 2025-10-14 01:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0014_delete_goal'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('template', models.CharField(blank=True, default='', max_length=60)),
                ('objective', models.CharField(blank=True, default='', max_length=300)),
                ('spec', models.JSONField(blank=True, default=dict)),
                ('model', models.CharField(blank=True, default='', max_length=60)),
                ('temperature', models.FloatField(default=0.4)),
                ('tokens', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_plans', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='finance_aip_user_id_b53abf_idx')],
            },
        ),
    ]
