# Generated by Django 5.2.4 on 2025-10-25 18:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0015_aiplan'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='is_archived',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['user', 'is_archived'], name='finance_cat_user_id_61e2b3_idx'),
        ),
    ]
