# Generated by Django 5.2.4 on 2025-10-25 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0016_category_is_archived_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
    ]
