# Generated by Django 5.2.4 on 2025-10-25 22:52

import django.db.models.functions.text
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0017_alter_category_is_archived'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='category',
            name='uniq_user_category_name_insensitive',
        ),
        migrations.RemoveConstraint(
            model_name='category',
            name='uniq_global_category_name_insensitive',
        ),
        migrations.AddConstraint(
            model_name='category',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('name'), models.F('user'), condition=models.Q(('is_archived', False)), name='uniq_user_category_name_insensitive'),
        ),
        migrations.AddConstraint(
            model_name='category',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('name'), condition=models.Q(('is_archived', False), ('user__isnull', True)), name='uniq_global_category_name_insensitive'),
        ),
    ]
